// Modern (cuda-oxide) build: embed the cubin produced ahead of time by
// ./build-cuda-oxide-kernels.sh. There is no LLVM 7 / rustc_codegen_nvvm
// involvement anywhere in this build; the cubin is generated by the
// cuda-oxide toolchain (rustc-codegen-cuda backend + LLVM 21 tools +
// CUDA 13 libnvvm/nvJitLink).
fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    let out_path = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let manifest_dir = std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let cubin = if cfg!(feature = "galpy-kepler-reference") {
        manifest_dir.join("target/cuda-oxide/galpy-kepler-reference/kernels.cubin")
    } else {
        manifest_dir.join("target/cuda-oxide/kernels.cubin")
    };

    println!("cargo::rerun-if-changed={}", cubin.display());

    std::fs::copy(&cubin, out_path.join("kernels.cubin")).unwrap_or_else(|err| {
        panic!(
            "failed to copy cuda-oxide cubin from {}: {err}. Run ./build-cuda-oxide-kernels.sh with matching features first",
            cubin.display()
        )
    });
}
