[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[project]
name = "astrodrift"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies = [
    "astropy>=7.1.1",
    "galpy>=1.11.1",
    "numpy>=1.24.4",
    "pandas>=2.0.3",
    "patchelf>=0.17.2.4",
]

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "python"
module-name = "drift.drift_rs"
[profile.dev]
rustflags = ["-Dwarnings"]

[profile.release]
rustflags = ["-Dwarnings"]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-cov>=5.0.0",
]
[tool.pytest.ini_options]
addopts = "--maxfail=1 --cov=drift --cov-report=term-missing"




